// GLobal vars
export const GLOBAL_CHANGE_NAME = "GLOBAL/CHANGE_NAME"
export const GLOBAL_TOGGLE_LOGGED = "GLOBAL/TOGGLE_LOGGED"

// View notification
export const NOTIF_SHOW = "NOTIFICATION/TRUE_VISIBLE"
export const NOTIF_CLOSE = "NOTIFICATION/FALSE_VISIBLE"

// Works with reports
export const REPORT_CHANGE_TYPE = "REPORT/CHANGE_TYPE"
export const REPORT_CHANGE_GROUP = "REPORT/CHANGE_GROUP"
export const REPORT_CHANGE_SUBJECT = "REPORT/CHANGE_SUBJECT"
export const REPORT_CHANGE_TYPE_SUBJECT = "REPORT/CHANGE_TYPE_SUBJECT"
