// GLobal vars
export const GLOBAL_INIT                  = "GLOBAL/INIT"
export const GLOBAL_CHANGE_NAME_TEACHER   = "GLOBAL/CHANGE_NAME"
export const GLOBAL_TOGGLE_LOGGED         = "GLOBAL/TOGGLE_LOGGED"

export const SCHEDULE_SET_SCHEDULE        = "SCHEDULE/SET_SCHEDULE"

// View notification
export const NOTIF_SHOW    = "NOTIFICATION/TRUE_VISIBLE"
export const NOTIF_CLOSE   = "NOTIFICATION/FALSE_VISIBLE"

// Works with reports
export const REPORT_CHANGE_TYPE           = "REPORT/CHANGE_TYPE"
export const REPORT_CHANGE_GROUP          = "REPORT/CHANGE_GROUP"
export const REPORT_CHANGE_SUBJECT        = "REPORT/CHANGE_SUBJECT"
export const REPORT_CHANGE_TYPE_SUBJECT   = "REPORT/CHANGE_TYPE_SUBJECT"
export const REPORT_CHANGE_PRIORITY       = "REPORT/CHANGE_PRIORITY"
export const REPORT_GET_DATA              = "REPORT/GET_DATA"
export const REPORT_SAVE_DATA             = "REPORT/SAVE_DATA"
export const REPORT_RENDER_DATA           = "REPORT/RENDER_DATA"

// Edit report
export const REPORT_EDIT_CHANGE_STATE     = "REPORT/EDIT_CHANGE_STATE"
export const REPORT_EDIT_ADD_CHANGE       = "REPORT/EDIT_ADD_CHANGE"
export const REPORT_FULLUPDATE_DATA       = "REPORT/FULLUPDATE_DATA"
export const REPORT_EDIT_TO_BACK          = "REPORT/EDIT_TO_BACK"

// template
export const TEMPLATE_TOGGLE_EDIT         = "TEMPLATE/TOGGLE_EDIT"
export const TEMPLATE_CHANGE_MAX_THEAD    = "TEMPLATE/CHANGE_MAX_THEAD"
export const TEMPLATE_CHANGE_PROPS			= "TEMPLATE/CHANGE_PROPS"
export const TEMPLATE_ADD_PART				= "TEMPLATE/ADD_PART"
export const TEMPLATE_ADD_STUDENT			= "TEMPLATE/ADD_STUDENT"
export const TEMPLATE_DELETE_COL				= "TEMPLATE/DELETE_COL"

export const TEMPLATE_SAVE                = "TEMPLATE/SAVE"
